apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: impresion-params
  name: impresion-params
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: impresion-params
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.rancher.container.start_once: "true"
        service: impresion-params
    spec:
      containers:
      -
        command:
        - "sh"
        args:
        - -c
        - echo ${PARAM1} ${PARAM2}; sleep 1000
        env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        image: alpine
        imagePullPolicy: ""
        name: impresion-params
      restartPolicy: Always




apiVersion: v1
kind: ReplicationController
metadata:
  labels:
      app: impresion-params
  name: "impresion-test"
  namespace: "experiment1"
spec:
  replicas: 1
  selector:
    app: impresion-params
  template:
    metadata:
      labels:
        app: impresion-params
    spec:
      restartPolicy: Always
      containers:
      - image: "alpine"
        name: "testing"
        command:
          - sh
        args:
          - -c
          - echo HOLA QUE TAL; sleep 60
