# TODO: Delete this file?


version: '2'
services:
  mensajes1:
    image: alpine
    environment:
      PARAM1: ${PARAM1}
      PARAM2: ${PARAM2}
    stdin_open: true
    entrypoint:
    - sh
    - -c
    - echo $$PARAM1 $$PARAM2; sleep 1000
    tty: true


apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: ${SERVICE_NAME}
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: ${SERVICE_NAME}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.rancher.container.start_once: "true"
        service: ${SERVICE_NAME}
    spec:
      containers:
      - args:
        - TCP-LISTEN:${LOCAL_PORT},fork
        - TCP:${TARGET_URI}
        env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        image: verb/socat:alpine
        imagePullPolicy: ""
        name: ${SERVICE_NAME}
        securityContext:
          privileged: true
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
