version: '2'
services:
  mensajes1:
    image: alpine
    environment:
      PARAM1: ${PARAM1}
      PARAM2: ${PARAM2}
    stdin_open: true
    entrypoint:
    - sh
    - -c
    - echo $$PARAM1 $$PARAM2; sleep 1000
    tty: true


apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: impresion-params
  name: impresion-params
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: impresion-params
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.rancher.container.start_once: "true"
        service: impresion-params
    spec:
      containers:
      - entrypoint: "sh"
        args:
        - -c
        - echo $$PARAM1 $$PARAM2; sleep 1000
        env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        image: verb/socat:alpine
        imagePullPolicy: ""
        name: impresion-params
      restartPolicy: Always