apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: botnet
  name: botnet
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: botnet
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: botnet
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        image: innotech/botnet-behavior-create-agreements:1.0.1-21
        imagePullPolicy: ""
        name: botnet
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
