apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: orchestator
  name: orchestator
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: orchestator
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orchestator
        #io.rancher.container.agent.role: environment
        #io.rancher.container.create_agent: "true"
    spec:
      containers:
      - env:
        - name: INITIALIZE
          value: "curl --silent -d \'{\"users\": ${USERS}, \"products\": ${PRODUCTS}}\' botnet:8080/v1/behavior/create;"
        - name: NAMESPACE
          value: ${NAMESPACE}
        - name: KAFKA_SERVICE
          value: "${KAFKA_SERVICE}"
        - name: TOPIC
          value: "${ROOT_TOPIC}-metrics"
        image: ${ORCHESTATOR_IMAGE}
        imagePullPolicy: ""
        name: orchestator
        ports:
        - containerPort: 9999
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
