apiVersion: v1
kind: ReplicationController
# TODO: Terminar adaptacion para el replication controler
metadata:
  creationTimestamp: null
  labels:
    service: experiment-launcher
  name: experiment-launcher
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: experiment-launcher
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.rancher.container.start_once: "true"
        service: experiment-launcher
    spec:
      containers:
      - entrypoint: "sh"
        args:
        - -c
        - echo $$PARAM1 $$PARAM2; sleep 1000
        env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        image: verb/socat:alpine
        imagePullPolicy: ""
        name: experiment-launcher
      restartPolicy: Always
