apiVersion: v1
kind: ReplicationController
# TODO: Terminar adaptacion para el replication controler
metadata:
  creationTimestamp: null
  labels:
    service: experiment-launcher
  name: experiment-launcher
spec:
  replicas: 1
  selector:
    service: experiment-launcher
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.rancher.container.start_once: "true"
        service: experiment-launcher
    spec:
      containers:
      -
        command:
        - "sh"
        args:
        - -c
        - python
        - ${url_entradas}
        - ${access_key}
        - ${secret_key}
        image: automodeling/automodeling:1.0.0
        imagePullPolicy: ""
        name: experiment-launcher
      restartPolicy: Always
