apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: bokeh-plotter
    traefik.domain: ${TRAEFIK_DOMAIN}
    traefik.enable: "true"
    traefik.port: "5006"
  name: bokeh-plotter
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: bokeh-plotter
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: bokeh-plotter
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        - name: KAFKA_SERVICE
          value: "${KAFKA_SERVICE}"
        - name: TOPIC
          value: "${ROOT_TOPIC}-metrics"
        - name: TRAEFIK_DOMAIN
          value: "${TRAEFIK_DOMAIN}"
        image: innotech/bokeh-plotter:0.1.0-7
        imagePullPolicy: ""
        name: bokeh-plotter
        ports:
        - containerPort: 5006
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5006
          timeoutSeconds: 3
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
