apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: etl-create-agreement
  name: etl-create-agreement
  namespace: ${NAMESPACE}
spec:
  replicas: ${NUM_ETL}
  selector:
    service: etl-create-agreement
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: etl-create-agreement
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        - name: PRODUCTS
          value: "${PRODUCTS}"
        - name: TOPIC
          value: "${ROOT_TOPIC}-botnet-output"
        - name: TOPIC_OUTPUT
          value: "${ROOT_TOPIC}-etl-output"
        - name: INPUT_KAFKA
          value: "${KAFKA_SERVICE}"
        - name: KAFKA_GROUP
          value: "${ROOT_TOPIC}-botnet-output-consumer"
        - name: OUTPUT_KAFKA
          value: "${KAFKA_SERVICE}"
        image: innotech/etl-create-agreement:0.2.0-17
        imagePullPolicy: ""
        name: etl-create-agreement
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
