.catalog:
  description: |
    Generic and configurable neural network using tensorflow. {{DATE}}.
  minimum_rancher_version: v0.46.0
  name: ml-ex-neural-network-tf
  questions:
  - default: experiment
    description: Make sure the Namespace exists or you will not be able to see the
      service
    label: Kubernetes Namespace
    required: true
    type: string
    variable: NAMESPACE
  - default: innotech/generic-neural-network-tensorflow:latest
    label: 'Neural Network Image:'
    required: true
    type: string
    variable: TF_IMAGE
  - default: innotech/orchestator:2.0.0-46
    label: 'Orchestator Image:'
    required: true
    type: string
    variable: ORCHESTATOR_IMAGE
  - default: ml-kube.innotechapp.com
    description: Domain name to route rule
    label: 'Traefic domain:'
    required: false
    type: string
    variable: TRAEFIK_DOMAIN
  - default: kafka.default
    description: Name of the Kafka broker to use including the namespace
    label: 'Kafka:'
    required: true
    type: string
    variable: KAFKA_SERVICE
  - default: ml-ex-tf
    description: Basename for topics
    label: 'Root topic:'
    required: true
    type: string
    variable: ROOT_TOPIC
  - default: http://artifactory.ml.innotechapp.com/artifactory/ml/innotech/tensorflow_models/
    description: URI of the repository where the model will be persisted
    label: 'Model repository URI:'
    required: true
    type: string
    variable: REPO_URI
  - default: false
    description: Recover previous training from artifactory
    label: Recover training
    options:
    - false
    - true
    required: true
    type: enum
    variable: RECOVER_SESSION
  - default: "100"
    description: Number of products
    label: 'Products:'
    required: true
    type: int
    variable: PRODUCTS
  - default: "30"
    description: 'Size of the hidden layers separated by commas. Example: 30,30'
    label: 'Hidden layers size:'
    required: true
    type: string
    variable: HIDDEN_SIZE
  - default: "300"
    description: Number of input samples used in each iteration
    label: 'Batch size:'
    required: true
    type: int
    variable: BATCH_SIZE
  - default: "4"
    description: Number of iterations for each batch
    label: 'Epochs:'
    required: true
    type: int
    variable: EPOCHS
  - default: "1"
    description: Number of batches between metric output
    label: 'Metric Interval:'
    required: true
    type: int
    variable: METRIC_INTERVAL
  - default: "5"
    description: 5 means 1/5
    label: 'Test size:'
    required: true
    type: int
    variable: TEST_SIZE
  - default: "120"
    description: Number of seconds before saving the network to artifactory
    label: 'Save interval:'
    required: true
    type: int
    variable: SAVE_INTERVAL
  - default: "300"
    description: Number of botnet users
    label: 'Users:'
    required: true
    type: int
    variable: USERS
  - default: 1000
    description: Time between botnet ticks
    label: 'Tick Duration (ms):'
    required: true
    type: int
    variable: TICK_DURATION
  - default: "1"
    description: Number of etl containers
    label: 'ETL scale:'
    required: true
    type: int
    variable: NUM_ETL
  version: 0.2.0
