apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: etl-create-agreement
  name: etl-create-agreement
  namespace: catalog1model1
spec:
  replicas: 1
  selector:
    service: etl-create-agreement
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: etl-create-agreement
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: catalog1model1
        - name: PRODUCTS
          value: "100"
        - name: TOPIC
          value: "catalog1model1-botnet-output"
        - name: TOPIC_OUTPUT
          value: "catalog1model1-etl-output"
        - name: INPUT_KAFKA
          value: "kafka.default"
        - name: KAFKA_GROUP
          value: "catalog1model1-botnet-output-consumer"
        - name: OUTPUT_KAFKA
          value: "kafka.default"
        image: innotech/etl-create-agreement:0.2.0-17
        imagePullPolicy: ""
        name: etl-create-agreement
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
