apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: database
    # OJO SI EL NOMBRE DEL SERVICIO CAMBIA, HAY QUE CAMBIAR EL ACCESO EN EL LANZADOR
  name: database
spec:
  replicas: 1
  selector:
    service: database
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
      - image: arangodb
        imagePullPolicy: Always
        name: arango-db
        env:
        - name: ARANGO_NO_AUTH
          value: "1"
        ports:
        - containerPort: 8529
        volumeMounts:
          - mountPath: /var/lib/arangodb3
            name: automodeling-database
      volumes:
      - name: automodeling-database
        hostPath:
          path: /automodeling
