apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: database
    # OJO SI EL NOMBRE DEL SERVICIO CAMBIA, HAY QUE CAMBIAR EL ACCESO EN EL LANZADOR
  name: arango-db
spec:
  replicas: 1
  selector:
    service: database
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
      - image: arangodb
        imagePullPolicy: Always
        name: arango-db
        env:
        - name: ARANGO_ROOT_PASSWORD
          value: ${db_password}
        ports:
        - containerPort: 8529
