apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: experiment-launcher
  name: experiment-launcher
spec:
  replicas: 1
  selector:
    service: experiment-launcher
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.rancher.container.start_once: "true"
        service: experiment-launcher
    spec:
      containers:
      - name: experiment-launcher
        command:
        - "sh"
        args:
        - -c
        - python lanzadorServicios.py ${url_entradas} ${access_key} ${secret_key}; sleep infinity
        image: automodeling/automodeling:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/src/myapp/results
          name: results-volume
      - name: webapp
        command:
        - "sh"
        args:
        - "-c"
        - "python server.py"
        image: automodeling/webapp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        volumeMounts:
        - mountPath: /usr/src/myapp/results
          name: results-volume
      - name: arango_db
        image: arangodb
        imagePullPolicy: Always
        ports:
          - containerPort: 8529
        volumeMounts:
        - mountPath: /var/lib/arangodb3
          name: arango
      volumes:
      - name: results-volume
        emptyDir: {}
      - name: arango
        emptyDir: {} 