apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: experiment-launcher
  name: experiment-launcher
spec:
  replicas: 1
  selector:
    service: experiment-launcher
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.rancher.container.start_once: "true"
        service: experiment-launcher
    spec:
      containers:
      - name: experiment-launcher
        command:
        - "sh"
        args:
        - -c
        - python lanzadorServicios.py ${url_entradas} ${access_key} ${secret_key}; sleep infinity
        image: automodeling/automodeling:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /results-launcher
          name: results-volume
      - name: webapp
        command:
        - "sh"
        args:
        - "-c"
        - "python server.py"
        image: automodeling/webApp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        volumeMounts:
        - mountPath: /results-launcher
          name: results-volume
      volumes:
      - name: results-volume
        hostPath:
          path: /results-automodeling
