apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: botnet-executor
  name: botnet-executor
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    service: botnet-executor
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: botnet-executor
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: ${NAMESPACE}
        - name: GENERATOR_HOST
          value: "http://botnet:8080"
        - name: TICK_DURATION
          value: "${TICK_DURATION}"
        - name: TOPIC
          value: "${ROOT_TOPIC}-botnet-output"
        - name: KAFKA_SERVICE
          value: "${KAFKA_SERVICE}"
        image: innotech/botnet-executor-kafka:1.1.0-11
        imagePullPolicy: ""
        name: botnet-executor
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
