apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: orchestator
  name: orchestator
  namespace: catalog1model1
spec:
  replicas: 1
  selector:
    service: orchestator
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orchestator
        #io.rancher.container.agent.role: environment
        #io.rancher.container.create_agent: "true"
    spec:
      containers:
      - env:
        - name: INITIALIZE
          value: "curl --silent -d \'{\"users\": 300, \"products\": 100}\' botnet:8080/v1/behavior/create;"
        - name: NAMESPACE
          value: catalog1model1
        - name: KAFKA_SERVICE
          value: "kafka.default"
        - name: TOPIC
          value: "catalog1model1-metrics"
        image: innotech/orchestator:2.0.0-46
        imagePullPolicy: ""
        name: orchestator
        ports:
        - containerPort: 9999
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
